
DROP TABLE VDIR_LINEA_PROGRAMA;

CREATE TABLE "VDIRMP"."VDIR_PLAN_PROGRAMA" 
   ("COD_PLAN_PROGRAMA" NUMBER(14,0) NOT NULL ENABLE,	 
	"COD_PLAN" NUMBER(6,0) NOT NULL ENABLE, 
	"COD_PROGRAMA" NUMBER(6,0) NOT NULL ENABLE, 
	"COD_ESTADO" NUMBER(6,0) NOT NULL ENABLE, 
	"COBERTURA_INICIAL" VARCHAR2(4000), 
	"COBERTURA_FINAL" VARCHAR2(4000), 
	 PRIMARY KEY ("COD_PLAN_PROGRAMA"), 	 
	 FOREIGN KEY ("COD_PLAN")
	  REFERENCES "VDIRMP"."VDIR_PLAN" ("COD_PLAN") ENABLE, 
	 FOREIGN KEY ("COD_PROGRAMA")
	  REFERENCES "VDIRMP"."VDIR_PROGRAMA" ("COD_PROGRAMA") ENABLE, 
	 FOREIGN KEY ("COD_ESTADO")
	  REFERENCES "VDIRMP"."VDIR_ESTADO" ("COD_ESTADO") ENABLE	 
) ;   
   

CREATE INDEX VDIR_PLAN_PROGRAMA_INDEX1 ON VDIR_PLAN_PROGRAMA (COD_PLAN);

CREATE INDEX VDIR_PLAN_PROGRAMA_INDEX2 ON VDIR_PLAN_PROGRAMA (COD_PROGRAMA);

CREATE INDEX VDIR_PLAN_PROGRAMA_INDEX3 ON VDIR_PLAN_PROGRAMA (COD_ESTADO);

CREATE UNIQUE INDEX VDIR_PLAN_PROGRAMA_INDEX4 ON VDIR_PLAN_PROGRAMA (COD_PLAN, COD_PROGRAMA);



ALTER TABLE VDIR_ESTADO  
MODIFY (COD_ESTADO NUMBER(6, 0) );

ALTER TABLE VDIR_ESTADO  
MODIFY (DES_ESTADO VARCHAR2(100 BYTE) NOT NULL);
