
  CREATE TABLE "VDIRMP"."VDIR_TIPO_VIA" 
   (	"COD_TIPO_VIA" NUMBER NOT NULL ENABLE, 
	"DES_TIPO_VIA" VARCHAR2(50 BYTE), 
	"COD_ESTADO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VDIR_TIPO_VIA_PK" PRIMARY KEY ("COD_TIPO_VIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

 CREATE TABLE "VDIRMP"."VDIR_ESTADO_CIVIL" 
   (	"COD_ESTADO_CIVIL" NUMBER NOT NULL ENABLE, 
	"DES_ESTADO_CIVIL" VARCHAR2(20 BYTE), 
	"COD_ESTADO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VDIR_ESTADO_CIVIL_PK" PRIMARY KEY ("COD_ESTADO_CIVIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  
  CREATE TABLE "VDIRMP"."VDIR_EPS" 
   (	"COD_EPS" NUMBER NOT NULL ENABLE, 
	"DES_EPS" VARCHAR2(100 BYTE), 
	"COD_ESTADO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VDIR_EPS_PK" PRIMARY KEY ("COD_EPS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  
  ALTER TABLE VDIR_PERSONA ADD (COD_EPS NUMBER );
  ALTER TABLE VDIR_PERSONA ADD (COD_ESTADO_CIVIL NUMBER);
  ALTER TABLE VDIR_PERSONA ADD (IND_TIENE_MASCOTA NUMBER);
  
  ALTER TABLE VDIR_PERSONA ADD CONSTRAINT PERSONA_EPS_FK FOREIGN KEY(COD_EPS) REFERENCES VDIR_EPS(COD_EPS) ENABLE;  
  ALTER TABLE VDIR_PERSONA ADD CONSTRAINT PERSONA_ESTADO_CIVIL_FK FOREIGN KEY(COD_ESTADO_CIVIL) REFERENCES VDIR_ESTADO_CIVIL(COD_ESTADO_CIVIL) ENABLE;
