ALTER TABLE VDIR_PERSONA 
ADD (DIR_TIPO_VIA NUMBER );

ALTER TABLE VDIR_PERSONA 
ADD (DIR_NUM_VIA VARCHAR2(10) );

ALTER TABLE VDIR_PERSONA 
ADD (DIR_NUM_PLACA VARCHAR2(20) );

ALTER TABLE VDIR_PERSONA 
ADD (DIR_COMPLEMENTO VARCHAR2(30) );
