--------------------------------------
-- SEQUENCE VDIR_SEQ_BENEFICIARIO_PROGRAMA
--------------------------------------
CREATE SEQUENCE VDIR_SEQ_BENEFICIARIO_PROGRAMA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999 MINVALUE 1;

--------------------------------------
-- SEQUENCE VDIR_SEQ_FACTURA
--------------------------------------
CREATE SEQUENCE VDIR_SEQ_FACTURA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999 MINVALUE 1;

--------------------------------------
-- SEQUENCE VDIR_SEQ_FACTURA_DETALLE
--------------------------------------
CREATE SEQUENCE VDIR_SEQ_FACTURA_DETALLE INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999 MINVALUE 1;


--------------------------------------
-- TABLE VDIR_BENEFICIARIO_PROGRAMA
--------------------------------------
ALTER TABLE VDIR_BENEFICIARIO_PROGRAMA ADD (COD_ESTADO NUMBER NOT NULL);

ALTER TABLE VDIR_BENEFICIARIO_PROGRAMA ADD CONSTRAINT VDIR_BENEFICIARIO_PROGRAM_FK1 FOREIGN KEY (COD_ESTADO) REFERENCES VDIR_ESTADO (COD_ESTADO) ENABLE;


--------------------------------------
-- TABLE VDIR_AFILIACION
--------------------------------------
ALTER TABLE VDIR_AFILIACION ADD CONSTRAINT VDIR_AFILIACION_PK PRIMARY KEY (  COD_AFILIACION ) ENABLE;

--------------------------------------
-- TABLE VDIR_FACTURA
--------------------------------------
ALTER TABLE VDIR_FACTURA ADD (COD_AFILIACION NUMBER(16) NOT NULL);

ALTER TABLE VDIR_FACTURA ADD CONSTRAINT VDIR_FACTURA_FK1 FOREIGN KEY (COD_AFILIACION) REFERENCES VDIR_AFILIACION (COD_AFILIACION) ENABLE;
