--------------------------------------
-- TABLE VDIR_FACTURA
--------------------------------------
ALTER TABLE VDIR_FACTURA MODIFY (VALOR_IMPUESTO NULL);

ALTER TABLE VDIR_FACTURA MODIFY (VALOR_PROMOCION NULL);

ALTER TABLE VDIR_FACTURA MODIFY (COD_TIPO_PAGO NULL);

ALTER TABLE VDIR_FACTURA MODIFY (COD_FORMA_PAGO NULL);

--------------------------------------
-- TABLE VDIR_FACTURA_DETALLE
--------------------------------------

ALTER TABLE VDIR_FACTURA_DETALLE MODIFY (VALOR_IMPUESTO NULL);
